import { VINE_VIEWBOX, VINE_STEMS, VINE_LEAVES, VINE_RIBS } from './vine-paths'

/**
 * Decorative vine echoing the botanical ornament on the practice's rack card.
 * Paths are generated by scripts/gen-vine.py. Colour comes from `currentColor`,
 * so set text colour (and opacity) on the className.
 */
export default function Vine({ className = '', flip = false }: { className?: string; flip?: boolean }) {
  return (
    <svg
      viewBox={VINE_VIEWBOX}
      className={className}
      aria-hidden="true"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.8"
      strokeLinecap="round"
      strokeLinejoin="round"
      preserveAspectRatio="xMidYMin slice"
      style={flip ? { transform: 'scaleX(-1)' } : undefined}
    >
      {VINE_STEMS.map((d) => (
        <path key={d} d={d} />
      ))}
      {VINE_LEAVES.map((d) => (
        <path key={d} d={d} fill="currentColor" stroke="none" />
      ))}
      {VINE_RIBS.map((d) => (
        <path key={d} d={d} strokeWidth="1" className="stroke-cream/70" />
      ))}
    </svg>
  )
}
