"""Generate the decorative vine SVG paths used in src/components/Vine.tsx.

One meandering stem with short side branches and teardrop leaves, in the
spirit of the botanical ornament on the practice's rack card. No curls or
tendrils (reviewed and rejected).

Run:  python3 scripts/gen-vine.py            # writes src/components/vine-paths.ts
      python3 scripts/gen-vine.py --preview  # also writes public/_vine-preview.html
"""
import math
import random
import sys

random.seed(7)
W, H = 240, 900


def pt(x, y):
    return f"{x:.1f} {y:.1f}"


def smooth_path(pts):
    """Catmull-Rom -> cubic bezier for a smooth stroke."""
    d = f"M{pt(*pts[0])}"
    for i in range(len(pts) - 1):
        p0 = pts[i - 1] if i > 0 else pts[i]
        p1, p2 = pts[i], pts[i + 1]
        p3 = pts[i + 2] if i + 2 < len(pts) else p2
        c1 = (p1[0] + (p2[0] - p0[0]) / 6, p1[1] + (p2[1] - p0[1]) / 6)
        c2 = (p2[0] - (p3[0] - p1[0]) / 6, p2[1] - (p3[1] - p1[1]) / 6)
        d += f" C{pt(*c1)} {pt(*c2)} {pt(*p2)}"
    return d


def leaf(base, angle, length, width):
    """Teardrop leaf from base point pointing along angle. Returns (fill, midrib)."""
    bx, by = base
    ca, sa = math.cos(angle), math.sin(angle)
    tx, ty = bx + ca * length, by + sa * length
    nx, ny = -sa, ca
    c1 = (bx + nx * width + ca * length * 0.4, by + ny * width + sa * length * 0.4)
    c2 = (bx - nx * width + ca * length * 0.4, by - ny * width + sa * length * 0.4)
    fill = f"M{pt(bx, by)} Q{pt(*c1)} {pt(tx, ty)} Q{pt(*c2)} {pt(bx, by)} Z"
    rib = f"M{pt(bx, by)} L{pt(bx + ca * length * 0.8, by + sa * length * 0.8)}"
    return fill, rib


stems, leaves, ribs = [], [], []

# Main stem meanders down the full height.
main = []
for i in range(13):
    t = i / 12
    y = 20 + t * (H - 40)
    x = W * 0.5 + math.sin(t * math.pi * 2.6) * W * 0.22
    main.append((x, y))
stems.append(smooth_path(main))

# At each node: a short side branch carrying a pair of leaves plus a tip leaf,
# and a larger leaf or two hugging the main stem.
for i in range(1, 12):
    x, y = main[i]
    side = 1 if i % 2 else -1
    bx, by = x + side * 44, y - 30
    branch = [(x, y), (x + side * 18, y - 9), (x + side * 32, y - 20), (bx, by)]
    stems.append(smooth_path(branch))
    tip_ang = math.atan2(by - (y - 20), bx - (x + side * 32))
    specs = [
        ((bx, by), tip_ang, 34, 10),                                   # tip leaf
        ((x + side * 20, y - 11), tip_ang + 0.95, 28, 8.5),            # pair, one side
        ((x + side * 26, y - 15), tip_ang - 0.95, 28, 8.5),            # pair, other side
        ((x, y + 6), math.pi / 2 + side * 1.15, 40, 12),               # big leaf on main stem
        ((x + side * 2, y + 34), math.pi / 2 - side * 1.0, 30, 9),     # smaller leaf lower down
    ]
    for base, ang, L, Wd in specs:
        f, r = leaf(base, ang + random.uniform(-0.1, 0.1), L * random.uniform(0.9, 1.1), Wd)
        leaves.append(f)
        ribs.append(r)

ts = [
    "// Generated by scripts/gen-vine.py. Do not edit by hand.",
    f"export const VINE_VIEWBOX = '0 0 {W} {H}'",
    f"export const VINE_STEMS = {stems!r} as const",
    f"export const VINE_LEAVES = {leaves!r} as const",
    f"export const VINE_RIBS = {ribs!r} as const",
    "",
]
with open("src/components/vine-paths.ts", "w") as f:
    f.write("\n".join(ts))
print("wrote src/components/vine-paths.ts")

if "--preview" in sys.argv:
    def paths(a, extra=""):
        return "".join(f'<path d="{d}" {extra}/>' for d in a)

    def svg(color):
        return (
            f'<svg viewBox="0 0 {W} {H}" width="260" height="975" fill="none" stroke="{color}" '
            f'stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">'
            f"{paths(stems)}{paths(leaves, f'fill=\"{color}\" stroke=\"none\"')}"
            f"{paths(ribs, 'stroke-width=\"1\" stroke=\"#f7f5ee\" opacity=\"0.6\"')}</svg>"
        )

    with open("public/_vine-preview.html", "w") as f:
        f.write(
            '<html><body style="margin:0;background:#f7f5ee;display:flex;gap:40px;padding:30px;'
            'font:14px Inter,sans-serif;color:#1f3d2b">'
            + "<div><p>Solid</p>" + svg("#1f3d2b") + "</div>"
            + "<div><p>Faint (as used on the site)</p>" + svg("rgba(31,61,43,0.16)") + "</div>"
            + "</body></html>"
        )
    print("wrote public/_vine-preview.html")
